### ISSUE TITLE
Compose Message Loses Focus with Apptentive 3.2.1 on Android 4.4.2 devices

### ISSUE THREAD

**Issue by jmoubry** [apptentive/apptentive-android#124] opened 2016-08-31 15:56 UTC
In Message Center, when I touch the message body to enter a message, it immediately loses focus every time I touch the message body area. This only happens on Android 4.4.2 devices (I've tried an LG G2 and Droid Razr Maxx). It works on my Nexus 6 running Android 5.0.1. The same behavior occurs in Apptentive 3.2.0 and 3.2.1.

**Comment by skykelsey** [comment] 2016-08-31 17:22
Hi @jmoubry, thanks for bringing this to our attention. I'll try to reproduce.

**Comment by Badspler** [comment] 2016-09-15 22:37
I have experienced this to on the following device:

Samsung Galaxy S5
Android: 5.0
Model number: SM-G900F

I have a 6.0 version of the same device and it is not having the issue described.

After experimenting with building at different versions, the bug looks like it was introduced in version 3.2.0 as I am not experiencing the bug when building at version 3.1.1

**Comment by skykelsey** [comment] 2016-09-15 22:39
Thanks for the additional info. I have a fix, and will be releasing a patch in the near future to address it.

**Comment by skykelsey** [comment] 2016-10-05 18:36
Fixed in 3.2.2

**Closed by skykelsey** 2016-10-05 18:36 UTC
