### ISSUE TITLE
Null pointer exception when open MessageCenter after close and reopen the app.

### ISSUE THREAD

**Issue by ffedeevp** [apptentive/apptentive-android#111] opened 2015-11-06 23:08 UTC
Full stacktrace:

Process: net.taringa.mobile.debug, PID: 32589
    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setVisibility(int)' on a null object reference
            at com.apptentive.android.sdk.module.messagecenter.view.holder.IncomingTextMessageHolder.updateMessage(IncomingTextMessageHolder.java:44)
            at com.apptentive.android.sdk.module.messagecenter.view.MessageAdapter.getView(MessageAdapter.java:314)
            at android.widget.AbsListView.obtainView(AbsListView.java:2346)
            at android.widget.ListView.measureHeightOfChildren(ListView.java:1280)
            at android.widget.ListView.onMeasure(ListView.java:1188)
            at android.view.View.measure(View.java:18788)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
            at android.view.View.measure(View.java:18788)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:901)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
            at android.view.View.measure(View.java:18788)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
            at android.view.View.measure(View.java:18788)
            at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
            at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
            at android.view.View.measure(View.java:18788)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
            at android.support.v7.internal.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
            at android.view.View.measure(View.java:18788)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
            at android.view.View.measure(View.java:18788)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
            at android.view.View.measure(View.java:18788)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
            at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
            at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
            at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
            at android.view.View.measure(View.java:18788)
            at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
            at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
            at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
            at android.view.View.measure(View.java:18788)
            at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
            at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1216)
            at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
            at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
            at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
            at android.view.Choreographer.doCallbacks(Choreographer.java:670)
            at android.view.Choreographer.doFrame(Choreographer.java:606)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.app.ActivityThread.main(ActivityThread.java:5417)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by barry-li** [comment] 2015-11-07 02:52
Thanks for reporting this! We have found the cause, and we will release a fix as soon as possible.

**Comment by ffedeevp** [comment] 2015-11-09 19:14
Thanks @barry-li !!  I hope you can resolve this soon to keep using apptentive.

**Comment by fedefarina** [comment] 2015-12-14 13:56
Hi guys, any advance on this? Thanks!

**Comment by skykelsey** [comment] 2015-12-14 19:14
This issue has been fixed in the 2.1.0 release. Please check it out!

**Closed by skykelsey** 2015-12-14 19:14 UTC
